### ISSUE TITLE
Is this project working / maintained?

### ISSUE THREAD

**Issue by alexmic** [hellofresh/klepto#109]
Hello! Firstly, thanks for your effort on Klepto, it's a very useful tool. I'm trying to dump some data from Postgres to stdout and I'm having a bunch of issues:

1. `IgnoreData` does not seem to be respected, the whole table is dumped.
2. The `Table` argument of `Relationships` is not respected either, it tries to join with `Tables.Name` instead.
3. The `Matchers` example does not work -- it does not apply the filter and dumps the whole table. I've verified the queries running on my Postgres instance and they are indeed not filtered. 

I've tried both TOML and YAML configuration files with the same results. Here's an extract from my configuration file:

```toml
[[Matchers]]
  Latest100Reviewers = "users.reviews > 0 ORDER BY users.created_at DESC LIMIT 100"

[[Tables]]
  Name = "users"
  [Tables.Anonymise]
    email = "EmailAddress"
    username = "UserName"
    name = "FullName"
  [Tables.Filter]
    Match = "Latest100Reviewers"

[[Tables]]
  Name = "reviews"
  [[Tables.Relationships]]
    ForeignKey = "user_id"
    ReferencedTable = "users"
    ReferencedKey = "id"
  [[Tables.Relationships]]
    ForeignKey = "product_id"
    ReferencedTable = "products"
    ReferencedKey = "id"
  [Tables.Filter]
    Match = "Latest100Reviewers"

[[Tables]]
  Name = "review_videos"
  [[Tables.Relationships]]
    ForeignKey = "review_id"
    ReferencedTable = "reviews"
    ReferencedKey = "id"
  [[Tables.Relationships]]
    Table = "reviews"
    ForeignKey = "user_id"
    ReferencedTable = "users"
    ReferencedKey = "id"
  [Tables.Filter]
    Match = "Latest100Reviewers"

[[Tables]]
  Name = "notifications"
  IgnoreData = true
```

I'd appreciate any pointers.
