### ISSUE TITLE
Sample usage on DigitsN 

### ISSUE THREAD

**Issue by itsmechlark** [hellofresh/klepto#129]
I'm not a golang developer. How can you use  DigitsN as Anonymise?

**Comment by lucasmdrs** [comment]
Hi @itsmechlark thank you for showing the interest and making a question.

I'll use a sample from our documentation in the [README](https://github.com/hellofresh/klepto#usage) to answer this.

Let's say you have the following configuration:
```toml
[[Tables]]
  Name = "users"
  [Tables.Anonymise]
    email = "EmailAddress"
    username = "FirstName"
    password = "SimplePassword"
  [Tables.Filter]
    Match = "users.status = 'active'"
    Limit = 10
    [Tables.Filter.Sorts]
      created_at = "desc"
```

in the `Tables.Anonymise` section you can see a mapping of column name and `fake` function types: 
| Column Name | Anonymise Func |
| - | - | 
| email | EmailAddress |
| username | FirstName |
| password | SimplePassword |

To use DigitsN function, all you need to do is set it to the column you want to apply it, for example:
```toml
[[Tables]]
  Name = "users"
  [Tables.Anonymise]
    email = "EmailAddress"
    username = "FirstName"
    password = "SimplePassword"
    my_digitsn_column = "DigitsN"
  [Tables.Filter]
    Match = "users.status = 'active'"
    Limit = 10
    [Tables.Filter.Sorts]
      created_at = "desc"
```

For more information about the available functions, please check [Anonymise](https://github.com/hellofresh/klepto#anonymise) section in the documentation or the [fake.go](https://github.com/hellofresh/klepto/blob/master/pkg/anonymiser/fake.go) generated file.

**Comment by itsmechlark** [comment]
BTW @lucasmdrs, I'm using v0.3.0. Thank you.

**Comment by lucasmdrs** [comment]
Sorry @itsmechlark, you're absolutely correct. Thank you for reporting that :slightly_smiling_face: 
Klepto is not supporting a few functions that require arguments at the moment, those are:
```
CharactersN
DigitsN
ParagraphsN
SentencesN
WordsN
CreditCardNum
EnFallback
FS
Password
Seed
SetLang
UseExternalData
Year
```

I'll take a look at this later on to see how we're going to proceed (drop the functions or add support for them)

**Comment by lucasmdrs** [comment]
@itsmechlark we discussed about it, as the file was generated it grabbed pretty much all exported functions, some not even related to data generation.

I'll remove some of the incompatible ones and add support to pass arguments to the ones that requires it.
This is however a low priority fix, so it might take a few time before these functions are properly supported:
```
CharactersN
DigitsN
ParagraphsN
SentencesN
WordsN
CreditCardNum
Password
Year
```

**Comment by lucasmdrs** [comment]
Hey @itsmechlark just release the fix for this issue, now you can use a config like this:

To use DigitsN function, all you need to do is set it to the column you want to apply it, for example:
```toml
[[Tables]]
  Name = "users"
  [Tables.Anonymise]
    email = "EmailAddress"
    my_digitsn_column = "DigitsN:5"
```
This will make run the DigitsN function with the arg `5` (number of digits). 
I have added some information on how to use this now, please check [Anonymise](https://github.com/hellofresh/klepto#anonymise) section in the README and the [fake.go](https://github.com/hellofresh/klepto/blob/master/pkg/anonymiser/fake.go) generated file to see the function signature for what function needs arguments and what they are.

Feel free to reply to this issue or create a new one if you have any further questions. :slightly_smiling_face:
