### ISSUE TITLE
Grabbing multiple subsets for the same table?

### ISSUE THREAD

**Issue by reidab** [hellofresh/klepto#139]
I've got a use case where I'm interested in grabbing:
1. Unmodified copies of the user records for our staff
2. Anonymized copies of some non-staff users

I tried defining two `[[Tables]]` blocks in the config, but only the first is executed. 

```toml
[[Tables]]
  Name = "users"
  IgnoreData = false

  [Tables.Filter]
    Match = "AdminUsers"

[[Tables]]
  Name = "users"
  IgnoreData = false

  [Tables.Filter]
    Match = "Latest100Users"

  [Tables.Anonymise]
    email = "EmailAddress"
    first_name = "FirstName"
```

I also tried using two separate config files, but I can't see a way to process only data and not the structure, so I run into an error because the tables already exist.

Is there a way to do this currently?
