### ISSUE TITLE
Reusable filters in config file

### ISSUE THREAD

**Issue by rafaeljesus** [hellofresh/klepto#90]
At the moment Klepto users needs to repeat the filter in the configuration file for every mapped table as follows:

```toml
[[Tables]]
  Name = "customer"
  [Tables.Filter]
    Match = "customer.status = 'active'"
    Limit = 1000
    [Tables.Filter.Sorts]
      "customer.created_at" = "desc"

[[Tables]]
  Name = "sales_order"
  # relationships omitted 
  [Tables.Filter]
    Match = "customer.status = 'active'"
    Limit = 1000
    [Tables.Filter.Sorts]
      "customer.created_at" = "desc"

[[Tables]]
  Name = "sales_order_item"
  # relationships omitted 
  [Tables.Filter]
    Match = "customer.status = 'active'"
    Limit = 1000
    [Tables.Filter.Sorts]
      "customer.created_at" = "desc"
```

A solution for this would be use mustache template capabilities:

```toml
latest_active_customers = "customer.status = 'active' order by customer.created_at desc limit 1000"

[[Tables]]
  Name = "customer"
  [Tables.Filter]
    {{ latest_active_customers }}

[[Tables]]
  Name = "sales_order"
  # relationships omitted 
  [Tables.Filter]
    {{ latest_active_customers }}

[[Tables]]
  Name = "sales_order_item"
  # relationships omitted 
  [Tables.Filter]
    {{ latest_active_customers }}
```
